---
- name: Update all system packages
  apt:
    state: latest
    update_cache: yes

- name: Install required system packages
  apt:
    state: latest
    update_cache: yes
    name:
      - python3
      - python3-pip
