---
- name: Install required system packages
  apt:
    state: latest
    update_cache: yes
    name:
      - python3
      - python3-pip

- name: Install docker python depedencies for ansible
  pip:
    name:
      - docker
      - docker-compose
    executable: pip3
