import { registerEnumType } from "type-graphql";

// WARNING: be very careful about editting this file
// as it is tied directly to the initial_values migration.
// DO NOT edit this file unless you know what you're doing.

export const YEARLY_MEMBERSHIP = {
  tag: "yearly-membership"
};

export const SEMESTERLY_MEMBERSHIP = {
  tag: "semesterly-membership"
};

// Computed types are not liked by enums for some reason
// investigate later
export enum MembershipTypes {
  YEARLY = "yearly-membership",
  SEMESTERLY = "semesterly-membership"
}
registerEnumType(MembershipTypes, {
  name: "MembershipTypes", // this one is mandatory
  description: "Different types of ACM memberships one can have." // this one is optional
});
