---
galaxy_info:
  author: Andrew Starr-Bochicchio
  description: Cross-distro installation of the DigitalOcean monitoring agent
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - wily
        - xenial
        - yakkety
        - xenial
        - zesty
        - artful
        - bionic
        - cosmic
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: EL
      versions:
        - 6
        - 7
  galaxy_tags:
    - cloud
    - monitoring
dependencies: []