unless Vagrant.has_plugin?("vagrant-docker-compose")
  system("vagrant plugin install vagrant-docker-compose")
  puts "Dependencies installed, please try the command again."
  exit
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  graphql_port = 80
  traefik_port = 8080

  config.vm.network(:forwarded_port, guest: graphql_port, host: graphql_port)
  config.vm.network(:forwarded_port, guest: traefik_port, host: traefik_port)

  config.vm.provision :docker
  config.vm.provision :docker_compose, yml: ["/vagrant/docker-compose.yml", "/vagrant/docker-compose.override.yml"], run: "always"
end
